const Menu = [
    {
      id: 1,
      image: "images/steal14.jpg",
      name: "Sambara",
      years: "1300CE", 
      category: "Men",
      description: "Saraswati is a symbol of knowledge and wisdom. Knowledge is supremely alluring",

    },
    
    {
      id: 2,
      image: "images/steal16.jpg",
      name: "Hanuman",
      years: "1300CE", 
      category: "Men",
      description: "Brass (heavily leaded zinc-brass) head cast using the lost wax (cireperdue) technique.",
    },
    {
      id: 3,
      image: "images/steal17.jpg",
      name: "Nataraja",
      years: "1200CE", 
      category: "Men",
      description: "A superb Nataraja murti to add to the auspiciousness of your space. On the back of the avidya-roopi",
    },
    {
      id: 4,
      image: "images/steal18.jpg",
      name: "Vasuki",
      years: "1300CE", 
      category: "Men",
      description: "Vasuki, the son of Kashyap and Kadru is the most powerful snake and an ardent devotee of Lord Shiva",
    },
    {
      id: 5,
      image: "images/steal19.jpg",
      name: "Durga",
      years: "1200CE", 
      category: "Men",
      description: "Durga in Hinduism, a principal form of the Goddess, also known as Devi and Shakti.",
    },
    {
      id: 6,
      image: "images/steal20.jpg",
      name: "Saraswati",
      years: "1100CE", 
      category: "Men",
      description: "Maa (Mother) Saraswati is a Hindu goddess who represents education, creativity, and music.",
    },
    {
      id: 7,
      image: "images/steal21.jpg",
      name: "Vishnu",
      years: "1000CE",
      category: "Men",
      description: "Vishnu also known as Narayana and Hari, is one of the principal deities of Hinduism",
    },
    {
      id: 8,
      image: "images/steal22.jpg",
      name: "Vishnu",
      years: "1000CE",
      category: "Men",
      description: "Vishnu also known as Narayana and Hari, is one of the principal deities of Hinduism",
    },
    {
      id: 9,
      image: "images/steal23.jpg",
      name: "Saraswati",
      years: "1100CE", 
      category: "Men",
      description: "Maa (Mother) Saraswati is a Hindu goddess who represents education, creativity, and music.",
    },
    {
      id: 10,
      image: "images/steal24.jpg",
      name: "Radhakrishna",
      years: "", 
      category: "Men",
      description: "Radha, in Hinduism, the gopi (milkmaid) who became the beloved of the god Krishna",
    },
    
    {
      id: 11,
      image: "images/steal25.jpg",
      name: "Saraswati",
      years: "1100CE", 
      category: "Men",
      description: "Maa (Mother) Saraswati is a Hindu goddess who represents education, creativity, and music.",
    },
    {
      id: 12,
      image: "images/steal26.jpg",
      name: "Krishna",
      years: "900CE", 
      category: "Men",
      description: "The Krishna who emerged from the blending of these figures was ultimately identified with the supreme god Vishnu-Narayana",
    },
    {
      id: 13,
      image: "images/steal27.jpg",
      name: "Shiva",
      years: "100CE", 
      category: "Men",
      description: "Shiva is the Supreme Lord who creates, protects and transforms the universe.",
    },
    {
      id: 14,
      image: "images/steal28.jpg",
      name: "Ayyapa",
      years: "500CE", 
      category: "Men",
      description: "Ayyappan, also called Dharmasastha and Manikandan, is a Hindu deity popular in Southern India,",
    },
    {
      id: 15,
      image: "images/steal29.jpg",
      name: "Ganesh",
      years: "400CE", 
      category: "Men",
      description: "Ganesha, also spelled Ganesh, also called Ganapati, elephant-headed Hindu god of beginnings",
    },
    {
      id: 16,
      image: "images/steal30.jpg",
      name: "Venkateswara",
      years: "", 
      category: "Men",
      description: "Lord Venkateswara popularly known as Balaji, Tirupati is famous for the Venkateswara temple ",
    },
    {
      id: 17,
      image: "images/steal31.jpg",
      name: "Vasuki",
      years: "1300CE", 
      category: "Men",
      description: "Vasuki, the son of Kashyap and Kadru is the most powerful snake and an ardent devotee of Lord Shiva"
    },
    {
      id: 18,
      image: "images/steal32.jpg",
      name: "Saraswati",
      years: "1100CE", 
      category: "Men",
      description: "Maa (Mother) Saraswati is a Hindu goddess who represents education, creativity, and music.",
    },
    {
      id: 19,
      image: "images/steal33.jpg",
      name: "Hanuman",
      years: "1300CE", 
      category: "Men",
      description: "Brass (heavily leaded zinc-brass) head cast using the lost wax (cireperdue) technique.",
  
    },
    {
      id: 20,
      image: "images/steal34.jpg",
      name: "Durga",
      years: "1200CE", 
      category: "Men",
      description: "Durga in Hinduism, a principal form of the Goddess, also known as Devi and Shakti.",
 
    },
    {
      id: 21,
      image: "images/steal35.jpg",
      name: "Kaali",
      years: "1200CE", 
      category: "Men",
      description: "Durga in Hinduism, a principal form of the Goddess, also known as Devi and Shakti.",
   },
    {
      id: 22,
      image: "images/steal36.jpg",
      name: "Brama",
      years: "200CE", 
      category: "Men",
      description: "Brama is a genus of marine ray-finned fishes from the family Bramidae, the pomfrets.",
    },
    {
      id: 23,
      image: "images/steal37.jpg",
      name: "Vishnu",
      years: "1000CE",
      category: "Men",
      description: "Vishnu also known as Narayana and Hari, is one of the principal deities of Hinduism",
    
    },
    {
      id: 24,
      image: "images/steal38.jpg",
      name: "Kaali",
      years: "1200CE", 
      category: "Men",
      description: "Durga in Hinduism, a principal form of the Goddess, also known as Devi and Shakti.",
  
    },
    {
      id: 25,
      image: "images/steal39.jpg",
      name: "Venkateswara",
      years: "", 
      category: "Men",
      description: "Lord Venkateswara popularly known as Balaji, Tirupati is famous for the Venkateswara temple ",
 
    },
    {
      id: 26,
      image: "images/steal40.jpg",
      name: "Garuda",
      years: "1300CE", 
      category: "Men",
      description: "Garuda is a Hindu demigod and divine creature mentioned in the Hindu, Buddhist and Jain faiths.",
    },
    {
      id: 27,
      image: "images/steal16.jpg",
      name: "Hanuman",
      years: "1300CE", 
      category: "Men",
      description: "Brass (heavily leaded zinc-brass) head cast using the lost wax (cireperdue) technique.",
   },
    {
      id: 28,
      image: "images/steal12.jpg",
      name: "Buddha",
      years: "1500CE", 
      category: "Men",
      description: "Siddhartha Gautama, most commonly referred to as the Buddha, was a wandering ascetic ",
    },
    {
      id: 29,
      image: "images/steal11.jpg",
      name: " Yama Dharmaraja",
      years: "", 
      category: "Men",
      description: "Yama is the judge of the dead, while Dharmadeva is one of the Prajapatis",
    },
    {
      id: 29,
      image: "images/steal11.jpg",
      name: " Yama Dharmaraja",
      years: "", 
      category: "Men",
      description: "Yama is the judge of the dead, while Dharmadeva is one of the Prajapatis",
    },
  
  ];


  
  
  export default Menu;